language: python
python: 3.5
env:
  - TOX_ENV=py27-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py27-dj110
  - TOX_ENV=py27-dj111
  - TOX_ENV=py34-dj18
  - TOX_ENV=py34-dj19
  - TOX_ENV=py34-dj110
  - TOX_ENV=py34-dj111
  - TOX_ENV=py34-dj20
  - TOX_ENV=py35-dj18
  - TOX_ENV=py35-dj19
  - TOX_ENV=py35-dj110
  - TOX_ENV=py35-dj111
  - TOX_ENV=py35-dj20
  - TOX_ENV=py35-djmaster
  - TOX_ENV=py36-dj18
  - TOX_ENV=py36-dj19
  - TOX_ENV=py36-dj110
  - TOX_ENV=py36-dj111
  - TOX_ENV=py36-dj20
  - TOX_ENV=py36-djmaster
matrix:
  include:
    - python: "3.6"
      env: TOX_ENV=py36-dj111
    - python: "3.6"
      env: TOX_ENV=py36-dj20
    - python: "3.6"
      env: TOX_ENV=py36-djmaster
  allow_failures:
    - env: TOX_ENV=py35-djmaster
    - env: TOX_ENV=py36-djmaster
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
sudo: false
